---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
  #- ReadWriteOnce
  #- ReadOnlyMany
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
  volumeMode: Filesystem
  volumeName: my-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
  - vers=4.0
  nfs:
    server: example.com
    path: /path/to/data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs

